version: '3'

services:
  dynamo:
    image: dwmkerr/dynamodb
    command: "-sharedDb"
    hostname: dynamo
    volumes:
      - dynamodb:/data
    ports:
      - "8000:8000"

volumes:
  dynamodb:
    driver: local
